### ISSUE TITLE
Додай основний контент (e.g. avatar, name, job, contacts, intro, etc.) here.

### ISSUE THREAD

**Issue by bondxxl** [bondxxl/homepage#19]
- [ ] Primary content template
- [ ] Contact info items example (should be place inside the contact-info__block)
- [ ] Intro block (should be put below the previous container)
